### ISSUE TITLE
Move PyChaste website

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/PyChaste#34]
**Description**
Move the [PyChaste website](https://jmsgrogan.github.io/PyChaste/) to the Chaste organisation under [chaste.github.io](https://chaste.github.io)

**Related PRs**
* https://github.com/Chaste/Chaste.github.io/pull/17

**To Do**
- [x] Add PyChaste markdown pages to site (https://github.com/Chaste/Chaste.github.io/pull/17)
- [x] Automatically generate tutorial markdown (https://github.com/Chaste/PyChaste/pull/50)
- [x] Add landing page for PyChaste (https://github.com/Chaste/Chaste.github.io/issues/22)
- [x] Fix tutorial syntax highlighting (https://github.com/Chaste/Chaste.github.io/issues/22)
- [ ] Move PyChaste Python API docs (https://github.com/Chaste/Chaste.github.io/issues/22)
- [ ] Update PyChaste pages for trunk merge: https://github.com/Chaste/Chaste.github.io/pull/101
- [ ] Add PyChaste Dev Guide #47

**Comment by kwabenantim** [comment]
Previous [deployment failed](https://github.com/Chaste/PyChaste/actions/runs/6096204748), possibly due to permissions issues.

**Comment by kwabenantim** [comment]
The old Jekyll site is now deployed to https://chaste.github.io/PyChaste.
It probably needs redoing to match the modern Hugo theme on https://chaste.github.io.

**Comment by kwabenantim** [comment]
> It probably needs redoing to match the modern Hugo theme on https://chaste.github.io.

As part of #46, content from the PyChaste website will be moved into [chaste.github.io](https://chaste.github.io)

**Comment by kwabenantim** [comment]
The PyChaste website is being re-created in markdown directly under chaste.github.io (see PR https://github.com/Chaste/Chaste.github.io/pull/17).

Things to consider for python notebook tutorials:
* Generate markdown from ipynb automatically to keep them in sync.
* Create cron job to periodically check current ipynb against markdown and update markdown manually.

**Comment by kwabenantim** [comment]
[nbconvert](https://github.com/jupyter/nbconvert) can help with the automatic conversion of Jupyter notebooks to markdown.

**Comment by kwabenantim** [comment]
Generating markdown for the website is fixed in this PR: https://github.com/Chaste/PyChaste/pull/50

**Comment by kwabenantim** [comment]
Python is not specified in the code blocks for some of the generated tutorial markdown, which affects syntax highlighting on the website.

**Bad Example**
```
import os
def main:
    print("Code block without 'python'")
```
https://chaste.github.io/pychaste/tutorials/pottsbasedcellsimulations/

**Good Example**
```python
import os
def main:
    print("Code block with 'python'")
```
https://chaste.github.io/pychaste/tutorials/cellsorting/

**Resolution**
The bad examples are duplicate tutorials that were not overwritten with autogenerated ones. They will be removed.

**Comment by kwabenantim** [comment]
As part of #46, PyChaste API generation will be moved to Chaste infra.
