### ISSUE TITLE
Unify Chaste and PyChaste docker images

### ISSUE THREAD

**Issue by kwabenantim** [Chaste/PyChaste#56]
**Summary**

Pros:
* One docker image for everything Chaste.
* Using dependencies from the Ubuntu repository that work together instead of trying to resolve conda-forge dependency conflicts for PyChaste (although this will still need to be done for the PyChaste conda package).

Cons:
* Larger image: chaste-docker (~2.2 GB) + pychaste-docker(~700 MB) - overlapping dependencies.
* Need to work out what happens when a container launches. For the PyChaste image, it automatically launches a Jupyter notebook.

**Comment by kwabenantim** [comment]
**TODO**
- [x] Create image with pychaste and check if resulting size is reasonable.
- [ ] Maintain current terminal interface as default and add extra instructions for launching with a Jupyter notebook e.g. adding an extra environment variable.

**Comment by kwabenantim** [comment]
### Note from discussion

Find out if theres's a suitable workaround for removing PyChaste dependency on Xvfb.

### Potential alternatives to Xvfb

**EGL (headless rendering on GPU or CPU)**
* `EGL` support defaults to `TRUE` in [VTK build options](https://docs.vtk.org/en/latest/build_instructions/build_settings.html) for Linux; may already be supported in standard Ubuntu VTK build (need to check this).
* Pre-built VTK with EGL support [available from conda-forge](https://anaconda.org/channels/conda-forge/packages/vtk/files).
* Building a custom VTK with [EGL support](https://docs.pyvista.org/extras/building_vtk.html#off-screen-plotting-gpu-support) (`VTK_OPENGL_HAS_EGL=TRUE`):
    * Default to headless rendering mode (`VTK_DEFAULT_RENDER_WINDOW_HEADLESS=TRUE`).
    * Optionally, disable normal X rendering mode (`VTK_USE_X=FALSE`).

**OSMesa (headless rendering on CPU)**
* Pre-built VTK with [OSMesa](https://mesa-docs.readthedocs.io/en/latest/osmesa.html) support [available from conda-forge](https://anaconda.org/channels/conda-forge/packages/vtk/files).
* Building custom VTK with [OSMesa support](https://docs.pyvista.org/extras/building_vtk.html#building-osmesa) (`VTK_OPENGL_HAS_OSMESA=TRUE`):
    * Default to headless rendering mode (`VTK_DEFAULT_RENDER_WINDOW_HEADLESS=TRUE`).
    * Optionally, disable normal X rendering mode (`VTK_USE_X=FALSE`).

**Switching to headless rendering**
With EGL/OSMesa support enabled,
 * Set an [environment variable](https://docs.vtk.org/en/latest/advanced/runtime_settings.html#opengl) to use off-screen rendering
     * `VTK_DEFAULT_OPENGL_WINDOW=vtkEGLRenderWindow `
     * `VTK_DEFAULT_OPENGL_WINDOW=vtkOSOpenGLRenderWindow`
 * Alternatively, perform all PyChaste rendering off-screen only [[C++ example](https://examples.vtk.org/site/Cxx/Utilities/OffScreenRendering/)] [[Python example](https://examples.vtk.org/site/PythonicAPI/Utilities/OffScreenRendering/)]

**VTK 9.4+**
From [VTK 9.4](https://docs.vtk.org/en/latest/release_details/9.4/support-runtime-opengl-window-selection.html),
> On Linux, VTK will now automatically fallback to EGL when there is no X display present or it is not capable of OpenGL. In case the system is not configured for EGL, VTK will fallback to OSMesa. 

[Standard VTK package now has headless rendering support](https://discourse.vtk.org/t/status-update-runtime-opengl-render-window-selection-in-vtk/14583)
> Starting from VTK 9.4, scheduled for November, 2024, your project can rely on just a single vtk package for onscreen, offscreen and headless rendering.


**VTK.js or VTK.wasm**

Does rendering directly in the browser [using WebGL](https://www.kitware.com//vtk-js-the-visualization-toolkit-on-the-web/) or [wasm](https://www.kitware.com/bring-powerful-3d-visualization-to-the-browser-with-vtk-wasm/) .

**Comment by bdevans** [comment]
**Further notes**

Presently the `chaste/base` image without `pychaste` is 3.4GB. With `pychaste` (built with the changes in https://github.com/Chaste/chaste-docker/tree/pychaste) this rises to 10GB. 

Suggestion: create a new CI workflow to build `chaste/base-pychaste` as a separate image from `chaste/base` and from there build `chaste/develop` and `chaste/develop-pychaste` etc.

**Comment by bdevans** [comment]
See also #17 (and #369) which may be dependencies for closing this issue.

**Comment by kwabenantim** [comment]
### Tasks

**Primary (native build)**
- [x] Generate PyChaste bindings on Questing Quokka with native Clang version (or pin to supported version if necessary)

**Secondary (conda build, etc.)**
- [x] Add XSD to conda-forge so there's a Mac version built as well. https://github.com/Chaste/PyChaste/issues/17
- [x] Setup infrastructure scripts for automatically building conda package to `pychaste` channel on Chaste repository. https://github.com/Chaste/Chaste/issues/547
- [ ] ~~Consider setting up `pychaste` build on conda-forge~~ (keep on pychaste channel for now, which also hosts xsd dependency)
- [x] Slim down PyChaste build
  -  pybind11 `OPT_SIZE` flag
  - no debug symbols in wrappers (`-g0`, https://github.com/Chaste/Chaste/pull/551/changes/19c4b768494db907e2de4ae273adf358b84ebd38)
  - combine templated wrappers(https://github.com/Chaste/cppwg/pull/94)
- [x] Reduce PyChaste build time after re-generating wrappers (https://github.com/Chaste/cppwg/issues/74)
- [ ] Install python package into virtualenv at standard location in image instead of problematic `--user`

**Comment by kwabenantim** [comment]
PyChaste wrappers can now be built at 1/3 the build size and speed. (https://github.com/Chaste/cppwg/pull/94)

Next Steps:
- Consolidate PyChaste install with all other python packages into one standard Chaste virtual environment (possibly with `--system-site-packages` on)
